### ISSUE TITLE
А это случайно не должен быть закрытый репозиторий?

### ISSUE THREAD

**Issue by AndrewChe7** [C4be/RomkaStrekalov#1]
> `clang format -i *.c` + файл `.clang-format` - форматирует все сишные файлы под один стиль.

Можете еще глянуть в сторону `indent`, там выравнивание задается через флаги.

> `cppcheck -q --enable=all ./<file>.c` - проверка на хорошее правило кода *(ХУЕТА БЕСЯЧАЯ)*

`cppcheck` - один из самых слабых статических анализаторов, чекайте [clang-sa](https://clang-analyzer.llvm.org/), да и вообще и то, и другое нормально прикручивается к редактору кода.

> но блять прогать на си на яблочном компе, это просто какой-то мазохизм. 

Ложь, пиздеж и провокация. Просто вам имеет смысл юзать clang вместо gcc, он весьма неплохо поддерживает яблочное железо, да и разрабатывался частично эпплами. 

> ЧТО НА ЭТИХ КОМПАХ ДЛЯ ХИПСТЕРОВ НЕТ НОРМАЛЬНЫХ УТИЛИТ

надо было ставить линукс, лол.

> ПРОГЕРЫ ПЕЙТЕ ВОДУ ИЗ БАЙКАЛА ФУНКЦИЯ НЕ ДОЛЖНА БЫТЬ БОЛЬШЕ 40 СТРОК

Ну вроде обычно ограничивают размером экрана, но это все хуета.

> АЙТИШНИКИ ВЛОЖЕННОСТЬ БОЛЬШЕ 4 РАЗ ЭТО ПРЯМ ЗАШКВАР

А вот это по факту. Вообще есть ряд приемов для избавления от лишней вложенности.

> надо создать триллиард функций которые будут разбросаны по коду, которые с горящей ЖОПОЙ  головой хер найдешь.

Ctrl-тык по функции работает в большинстве редакторов.

> 2) Код стайл

БАЗА

> глобальных пекременных

Функциональщики закурили в сторонке.

> которые принимают 12 аргументов, отрисовкой с 15 аргументами и физикой с 13 аргументами

Разбей функцию на несколько и аргументов поуменьшится, ну и плюс к тому некоторые данные можно объединить в структуру.

> пишешь всю эту залупу в одно рыло.

Польская нотация это не сложно. Если ты считаешь, что это сложно, то твой преподаватель - ублюдок.

> ЫЫЫ ОНА ЛОМАЕТСЯ

Тестить надо.

> нужно добавить & в scanf

БАЗА

**Comment by C4be** [comment]
Привет, ну по факту да, я открыл на время, так как знакомый попросил глянуть.
Подскажи как ты отыскал репу?

**Comment by C4be** [comment]
Там просто рамки очень ограничены по кодсталу и тп. Приходится большую часть дома делать, с помощью Clion, в котором много мощных инструментов для проверки анализа кода.  А так я полностью согласен с твоими комментариями, но все это сложно делать на тех машинах и с ограничением по времени.

**Comment by AndrewChe7** [comment]
> Привет, ну по факту да, я открыл на время, так как знакомый попросил глянуть. Подскажи как ты отыскал репу?

Ну так я на Лехин аккаунт был подписан, github в ленте подкинул уже твой аккаунт, ну и я увидел, что последний репозиторий, в который ты коммитил, это этот репозиторий.
